
export const ENUM_DESTINATION_STATUS = {
    PAST: "PAST",
    UPCOMING: "UPCOMING",
    BUCKET_lIST: "BUCKET_LIST",
}

export const ENUM_COUPLE_STATUS = {
    PENDING: "Pending",
    ACCEPTED: "Accepted",
    REJECTED: "Rejected",
    BROKE_UP: "Broke_up"
}

export const ENUM_ACTIVITY_STATUS = {
    DONE: "Done",
    IN_PROGRESS: "In Progress",
}

export const ENUM_SPARK_STATUS = {
    ROMANTIC: "Romantic",
    DESIRE: "Desire",
}

export const ENUM_DATE_STATUS = {
    PROPOSED: "Proposed",
    ACCEPTED: "Accepted",
    COMPLETED: "Completed",
}

export const ENUM_NOTIFICATION_TYPE = {
    NEW_ORDER : "NEW_ORDER",
    ORDER_ACCEPTED : "ORDER_ACCEPTED",
    ORDER_ON_THE_WAY : "ORDER_ON_THE_WAY",
    ORDER_COMPLETED : "ORDER_COMPLETED",
    ORDER_CONFIRMED : "ORDER_CONFIRMED",
    ORDER_REJECTED : "ORDER_REJECTED",
    ORDER_CANCELLED : "ORDER_CANCELLED",
    PAYMENT_RECEIVED : "PAYMENT_RECEIVED",
    PAYMENT_COMPLETED : "PAYMENT_COMPLETED",
    PAYMENT_FAILED : "PAYMENT_FAILED",
    // SYSTEM_ALERT : "SYSTEM_ALERT"
}



